#!/usr/bin/env bash
# This script displays files in current directory without hidden files and removes prefix before first dash
for file in *
do
  if [ -f "$file" ] || [ -d "$file" ]
  then
    echo "$file" | cut -d'-' -f2-
  fi
done
